using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gestiones_backend.Migrations
{
    /// <inheritdoc />
    public partial class NombreDeLaMigracion_2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Quitar identity
            migrationBuilder.Sql("ALTER TABLE compromisos_pago ALTER COLUMN id_compromiso DROP IDENTITY IF EXISTS;");

            // 2. Cambiar tipo a varchar
            migrationBuilder.Sql("ALTER TABLE compromisos_pago ALTER COLUMN id_compromiso TYPE varchar(40);");

            // 3. Asignar gen_random_uuid() como valor por defecto
            migrationBuilder.Sql("ALTER TABLE compromisos_pago ALTER COLUMN id_compromiso SET DEFAULT gen_random_uuid();");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // 1. Eliminar default uuid
            migrationBuilder.Sql("ALTER TABLE compromisos_pago ALTER COLUMN id_compromiso DROP DEFAULT;");

            // 2. Cambiar a integer
            migrationBuilder.Sql("ALTER TABLE compromisos_pago ALTER COLUMN id_compromiso TYPE integer USING id_compromiso::integer;");

            // 3. Restaurar como identity
            migrationBuilder.Sql("ALTER TABLE compromisos_pago ALTER COLUMN id_compromiso ADD GENERATED BY DEFAULT AS IDENTITY;");
        }
    }
}
