using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gestiones_backend.Migrations
{
    /// <inheritdoc />
    public partial class guid_id_tipo_gestion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Eliminar FK de gestiones → tipos_gestion
            migrationBuilder.Sql("ALTER TABLE gestiones DROP CONSTRAINT IF EXISTS gestiones_id_tipo_gestion_fkey;");

            // Eliminar FK de tipos_gestion → tipos_gestion (padre)
            migrationBuilder.Sql("ALTER TABLE tipos_gestion DROP CONSTRAINT IF EXISTS tipos_gestion_id_padre_fkey;");

            // Eliminar identidad (obligatorio antes de cambiar de int a varchar)
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_tipo_gestion DROP IDENTITY IF EXISTS;");

            // Cambiar tipo de columna en tipos_gestion
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_tipo_gestion TYPE varchar(40);");
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_tipo_gestion SET DEFAULT gen_random_uuid();");

            // Cambiar tipo de columna en tipos_gestion.id_padre
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_padre TYPE varchar(40);");

            // Cambiar tipo de columna en gestiones.id_tipo_gestion
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_tipo_gestion TYPE varchar(40);");

            // Volver a crear FK en tipos_gestion.id_padre
            migrationBuilder.Sql(@"
        ALTER TABLE tipos_gestion 
        ADD CONSTRAINT tipos_gestion_id_padre_fkey 
        FOREIGN KEY (id_padre) 
        REFERENCES tipos_gestion(id_tipo_gestion);
    ");

            // Volver a crear FK en gestiones.id_tipo_gestion
            migrationBuilder.Sql(@"
        ALTER TABLE gestiones 
        ADD CONSTRAINT gestiones_id_tipo_gestion_fkey 
        FOREIGN KEY (id_tipo_gestion) 
        REFERENCES tipos_gestion(id_tipo_gestion);
    ");
        }



        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Eliminar FK gestiones → tipos_gestion
            migrationBuilder.Sql("ALTER TABLE gestiones DROP CONSTRAINT IF EXISTS gestiones_id_tipo_gestion_fkey;");

            // Eliminar FK tipos_gestion → tipos_gestion (padre)
            migrationBuilder.Sql("ALTER TABLE tipos_gestion DROP CONSTRAINT IF EXISTS tipos_gestion_id_padre_fkey;");

            // Cambiar tipo de columnas a integer (original)
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_tipo_gestion TYPE integer USING id_tipo_gestion::integer;");
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_padre TYPE integer USING id_padre::integer;");
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_tipo_gestion TYPE integer USING id_tipo_gestion::integer;");

            // Restaurar identidad (auto incremento)
            migrationBuilder.Sql("ALTER TABLE tipos_gestion ALTER COLUMN id_tipo_gestion ADD GENERATED BY DEFAULT AS IDENTITY;");

            // Restaurar FK tipos_gestion.id_padre → tipos_gestion.id_tipo_gestion
            migrationBuilder.Sql(@"
        ALTER TABLE tipos_gestion 
        ADD CONSTRAINT tipos_gestion_id_padre_fkey 
        FOREIGN KEY (id_padre) 
        REFERENCES tipos_gestion(id_tipo_gestion);
    ");

            // Restaurar FK gestiones.id_tipo_gestion → tipos_gestion.id_tipo_gestion
            migrationBuilder.Sql(@"
        ALTER TABLE gestiones 
        ADD CONSTRAINT gestiones_id_tipo_gestion_fkey 
        FOREIGN KEY (id_tipo_gestion) 
        REFERENCES tipos_gestion(id_tipo_gestion);
    ");
        }

    }
}
