using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gestiones_backend.Migrations
{
    /// <inheritdoc />
    public partial class NombreDeLaMigracion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Quitar la propiedad IDENTITY primero
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_gestion DROP IDENTITY IF EXISTS;");

            // 2. Cambiar el tipo a varchar
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_gestion TYPE varchar(40);");

            // 3. Establecer gen_random_uuid() como valor por defecto
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_gestion SET DEFAULT gen_random_uuid();");
        }


        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Eliminar default gen_random_uuid()
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_gestion DROP DEFAULT;");

            // Volver a integer
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_gestion TYPE integer USING id_gestion::integer;");

            // Restaurar IDENTITY
            migrationBuilder.Sql("ALTER TABLE gestiones ALTER COLUMN id_gestion ADD GENERATED BY DEFAULT AS IDENTITY;");
        }

    }
}
